# language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t binucci/react-test -f ./client/Dockerfile.dev ./client

script:
  # -e CI = true: makes the test quit when finished, instead of the default that is not exiting
  - docker run -e CI=true binucci/react-test npm test

after_success:
  - docker build -t binucci/multi-client ./client
  - docker build -t binucci/multi-nginx ./nginx
  - docker build -t binucci/multi-server ./server
  - docker build -t binucci/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push binucci/multi-client
  - docker push binucci/multi-nginx
  - docker push binucci/multi-server
  - docker push binucci/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-419106060738"
  bucket_path: "multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

