# language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t binucci/react-test -f ./client/Dockerfile.dev ./client

script:
  # -e CI = true: makes the test quit when finished, instead of the default that is not exiting
  - docker run -e CI=true binucci/react-test npm test

after_success:
  - docker build -t binucci/multi-client -f ./client
  - docker build -t binucci/multi-nginx -f ./nginx
  - docker build -t binucci/multi-server -f ./server
  - docker build -t binucci/multi-worker -f ./worker

